alphabetic:
  iPad:
    floating: "alphabetic_26_portrait"
    landscape: "ipad_alphabetic_26_landscape"
    portrait: "ipad_alphabetic_26_portrait"
  iPhone:
    landscape: "alphabetic_26_landscape"
    portrait: "alphabetic_26_portrait"
author: "BlackCCCat"
keyboard_switcher:
  iPhone:
    landscape: "keyboard_switcher_landscape"
    portrait: "keyboard_switcher_portrait"
name: "万象键盘"
numeric:
  iPad:
    floating: "numeric_9_portrait"
    landscape: "ipad_numeric_9_landscape"
    portrait: "ipad_numeric_9_portrait"
  iPhone:
    landscape: "numeric_9_landscape"
    portrait: "numeric_9_portrait"
panel:
  iPhone:
    landscape: "panel_landscape"
    portrait: "panel_portrait"
pinyin:
  iPad:
    floating: "pinyin_26_portrait"
    landscape: "ipad_pinyin_26_landscape"
    portrait: "ipad_pinyin_26_portrait"
  iPhone:
    landscape: "pinyin_26_landscape"
    portrait: "pinyin_26_portrait"
pinyin14:
  iPhone:
    landscape: "pinyin_14_landscape"
    portrait: "pinyin_14_portrait"
pinyin17:
  iPhone:
    landscape: "pinyin_17_landscape"
    portrait: "pinyin_17_portrait"
pinyin18:
  iPhone:
    landscape: "pinyin_18_landscape"
    portrait: "pinyin_18_portrait"
pinyin26:
  iPhone:
    landscape: "pinyin_26_landscape"
    portrait: "pinyin_26_portrait"
pinyin27:
  iPhone:
    landscape: "pinyin_27_landscape"
    portrait: "pinyin_27_portrait"
pinyin9:
  iPhone:
    landscape: "pinyin_9_landscape"
    portrait: "pinyin_9_portrait"
temp_pinyin:
  iPhone:
    landscape: "temp_pinyin_landscape"
    portrait: "temp_pinyin_portrait"