name: Create Release

on:
  push:
    tags:
      - '*'  # 在任何标签推送时触发该 action

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保获取完整的提交历史

      # 获取提交信息，获取前一个标签
      - name: Get commit history
        id: commits
        run: |
          echo "COMMIT_LIST=$(git log --oneline ${{ github.event.before }}..${{ github.sha }} --no-merges)" >> $GITHUB_ENV
          echo "PREV_TAG=$(git describe --tags --abbrev=0 ${GITHUB_SHA}^)" >> $GITHUB_ENV

      # 重命名文件
      - name: Rename files
        run: |
          mv Skin_Keyboard/万象/26键-万象.hskin Skin_Keyboard/万象/26-wanxiang.hskin

      # 创建 Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Changes since ${{ env.PREV_TAG }}:
            ${{ env.COMMIT_LIST }}
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          files: |
            Skin_Keyboard/万象/26-wanxiang.hskin
